//go:build darwin

// The macOS headful path: instead of launching chromium via a raw
// ExecAllocator (which shows up in the dock/app-switcher as "Google Chrome"
// — whatever the underlying binary's LaunchServices identity happens to
// be), duck wraps chromium in a tiny app bundle at ~/.duck/DuckWindow.app.
// Launching THAT via `open` gives the window its own dock identity ("Duck
// Window") while chromedp still drives it over CDP via a remote allocator.
//
// This is an interim "dress up chromium" step — see docs/WINDOW.md's
// backend note: the intended long-term backend is a native WKWebView
// duck-window.app, with this CDP path kept as the fallback / today's
// implementation.
package window

import (
	"fmt"
	"os"
	"path/filepath"
)

// RemoteDebugPort is the fixed CDP port the DuckWindow.app wrapper listens
// on. Distinct from DefaultPort (the control-API HTTP port) — this one is
// chromium's own --remote-debugging-port.
const RemoteDebugPort = 7335

const duckWindowBundleName = "DuckWindow.app"

// duckWindowInfoPlist renders Contents/Info.plist for the wrapper bundle.
func duckWindowInfoPlist() string {
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>Duck Window</string>
	<key>CFBundleDisplayName</key>
	<string>Duck Window</string>
	<key>CFBundleIdentifier</key>
	<string>cat.digibug.duck.window</string>
	<key>CFBundleExecutable</key>
	<string>duck-window</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>LSMinimumSystemVersion</key>
	<string>11.0</string>
	<key>LSUIElement</key>
	<false/>
</dict>
</plist>
`
}

// duckWindowLauncherScript renders the wrapper's executable: it execs the
// resolved chrome binary in app mode against a duck-owned profile and CDP
// port, forwarding any extra args (e.g. --headless for tests, though the
// darwin bundle path is only used headful in practice).
func duckWindowLauncherScript(chrome string, port int) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by duck (internal/window/bundle_darwin.go) — do not edit by hand;
# it is regenerated whenever its content would differ.
exec %q \
	--app=about:blank \
	--user-data-dir="$HOME/.duck/window-profile" \
	--remote-debugging-port=%d \
	--no-first-run \
	--no-default-browser-check \
	"$@"
`, chrome, port)
}

// ensureDuckWindowBundle writes (or rewrites) the ~/.duck/DuckWindow.app
// wrapper bundle so its Info.plist and launcher script match the current
// chrome binary and port, returning the bundle path. Idempotent: an
// up-to-date bundle is left untouched, matching the agent-notes pattern
// (command/agentdoc.go) of "write only when content differs".
func ensureDuckWindowBundle(home, chrome string, port int) (string, error) {
	if home == "" {
		return "", fmt.Errorf("no home directory")
	}
	bundle := filepath.Join(home, ".duck", duckWindowBundleName)
	macosDir := filepath.Join(bundle, "Contents", "MacOS")
	if err := os.MkdirAll(macosDir, 0o755); err != nil {
		return "", err
	}

	plistPath := filepath.Join(bundle, "Contents", "Info.plist")
	plist := duckWindowInfoPlist()
	if cur, err := os.ReadFile(plistPath); err != nil || string(cur) != plist {
		if err := os.WriteFile(plistPath, []byte(plist), 0o644); err != nil {
			return "", err
		}
	}

	scriptPath := filepath.Join(macosDir, "duck-window")
	script := duckWindowLauncherScript(chrome, port)
	needsWrite := true
	if cur, err := os.ReadFile(scriptPath); err == nil && string(cur) == script {
		if fi, statErr := os.Stat(scriptPath); statErr == nil && fi.Mode()&0o111 != 0 {
			needsWrite = false
		}
	}
	if needsWrite {
		if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
			return "", err
		}
	}

	return bundle, nil
}
